
name: Maven Test Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'master'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and test with Maven
      run: mvn -B verify --file pom.xml
